[build]
  builder = "nixpacks"
  buildCommand = "cd backend && npm install && npx tsc -p tsconfig.prod.json"
  startCommand = "node backend/dist/index.js"
  installPhase = "true"
  buildPhase = "true"
  runPhase = "true"

[deploy]
  startCommand = "node backend/dist/index.js"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 600
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 5
